import * as React from "react";
import { Nunito } from "next/font/google";
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from "@/components/ui/carousel";
import Image from "next/image";

const nunito = Nunito({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nunito",
});

const images = [
    "/pictures/bee_1.png",
    "/pictures/bird_1.png",
    "/pictures/buffolo_1.png",
    "/pictures/cat_1.png",
    "/pictures/chicken_1.png",
    "/pictures/cow_1.png",
    "/pictures/dog_1.png",
    "/pictures/duck_1.png",
    "/pictures/elephant_1.png",
    "/pictures/giraffe_1.png",
    "/pictures/hippo_1.png",
    "/pictures/lion_1.png",
    "/pictures/monkey_1.png",
    "/pictures/mouse_1.png",
    "/pictures/pig_1.png",
    "/pictures/polarbear_1.png",
    "/pictures/rabbit_1.png",
    "/pictures/seal_1.png",
    "/pictures/shark_1.png",
    "/pictures/squirrel_1.png"

];

export default function GalleryPage() {
  return (
    <div className={`${nunito.variable} font-nunito min-h-screen w-full overflow-x-hidden p-4`}>
      <div className="w-full bg-white  flex justify-center items-center"> 
        <div className="grid grid-cols-1 w-full">

            <h1 className="text-3xl sm:text-4xl md:text-6xl text-gray-900 font-bold  text-center lg:pt-10 md:pt-6 pt-4"> GALLERy For AI</h1>
            <p className="text-center text-sm lg:text-lg mt-2">The image below is an image generated by AI.</p>

            <div className="flex justify-center items-center w-full">
                <Carousel   opts={{ align: "start",}} 
                            className="w-full max-w-7xl lg:py-10 py-6">

                    <CarouselContent className="h-full  w-full md:w-4/5 lg:w-1/4 space-x-1">
                        {images.map((src, index) => (
                        <CarouselItem key={index}>
                            <div className=" border border-gray-200 p-4 rounded-xl ">

                            <Image
                                src={src}
                                alt={`View ${index + 1}`}
                                width={600}
                                height={400}
                                className="object-cover h-full rounded-xl"
                            />
                            </div>
                        </CarouselItem>
                        ))}
                    </CarouselContent>
                    <CarouselPrevious />
                    <CarouselNext />
                    
                </Carousel>
            </div>
        </div>
        
      </div>
    </div>
  );
}
